import { Container, Flex, Heading, Text } from "@chakra-ui/react";
import Layout from "components/Layout/Layout";
import client from "lib/client";

import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { GET_MENUS } from "queries/getMenus";

const Home: NextPage = (data: any) => {
  const headerMenu = data.headerMenu.edges;
  console.log("first", headerMenu);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout menu={headerMenu}>
        <Heading size={"4xl"}>Hello</Heading>
        {/* <Text>{data.generalSettingsUrl}</Text> */}
        <Flex as="ul">
          {headerMenu?.map((item: any) => (
            <Flex key={item.node.id} as="li">
              <Link href={item.node.path}>
                <a>{item.node.label}</a>
              </Link>
            </Flex>
          ))}
        </Flex>
      </Layout>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  // Query the homepage data.
  const { data } = await client.query({
    query: GET_MENUS,
    //variables: { slug: "homepage" },
  });

  // Pass data to the page via props.
  return {
    props: {
      headerMenu: data?.headerMenu,
    },
    revalidate: 60,
  };
};
